import { eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { productImages, products } from "../../drizzle/schema";
import { SIZE_OPTIONS, parseCatalogSizes } from "../../shared/catalog";
import { clearAdminSession, isAdminCredentials, issueAdminSession } from "../_core/adminAuth";
import { adminPortalProcedure, publicProcedure, router } from "../_core/trpc";
import { getDb } from "../db";
import { addDbProductImage, addDbVariant, createDbProduct, deleteDbProduct, deleteDbVariant, listDbAdminProducts, listDbOrders, updateDbOrderStatus, updateDbProduct, updateDbVariant } from "../dbCommerce";
import { storagePut } from "../storage";
import * as XLSX from "xlsx";

const moneyInput = z.string().regex(/^\d+(\.\d{1,2})?$/).refine(value => Number(value) > 0, "Price must be greater than zero");
const sizeInput = z.enum(SIZE_OPTIONS);
const variantInput = z.object({ name: sizeInput, price: moneyInput, salePrice: moneyInput.optional(), discountEnabled: z.boolean().optional(), stock: z.number().int().min(0) });
const importImage = z.object({ fileName: z.string().min(1).max(180), mimeType: z.enum(["image/jpeg", "image/png", "image/webp", "image/avif"]), base64: z.string().min(100).max(12_000_000) });
const cleanHeader = (value: unknown) => String(value ?? "").trim().toLowerCase().replace(/[^a-z0-9]+/g, "_");
const rowValue = (row: Record<string, unknown>, ...keys: string[]) => keys.map(key => row[cleanHeader(key)]).find(value => value !== undefined && value !== null && String(value).trim() !== "");
function parseImportVariants(rawSizes: unknown, rawStock: unknown, price: string, salePrice?: string) { const sizes = parseCatalogSizes(rawSizes); const selected = sizes.length ? sizes : ["One Size" as const]; const stockValues = String(rawStock ?? "").split(/[,|;]/).map(value => value.trim()).filter(Boolean); return selected.map((name, index) => { const stock = Number(stockValues[index] ?? stockValues[0] ?? 0); if (!Number.isInteger(stock) || stock < 0) throw new Error(`Invalid stock for ${name}`); return { name, price, salePrice, discountEnabled: Boolean(salePrice), stock }; }); }

export const adminRouter = router({
  login: publicProcedure.input(z.object({ username: z.string(), password: z.string().min(1) })).mutation(async ({ input, ctx }) => { if (!isAdminCredentials(input.username, input.password)) throw new Error("Invalid admin credentials"); await issueAdminSession(ctx.res, ctx.req); return { success: true } as const; }),
  logout: publicProcedure.mutation(({ ctx }) => { clearAdminSession(ctx.res, ctx.req); return { success: true } as const; }),
  me: publicProcedure.query(({ ctx }) => ({ authenticated: ctx.adminAuthenticated })),
  products: router({
    list: adminPortalProcedure.query(() => listDbAdminProducts()),
    create: adminPortalProcedure.input(z.object({ title: z.string().min(2), description: z.string().min(1), category: z.string().min(1), gender: z.enum(["men", "women", "unisex"]), slug: z.string().regex(/^[a-z0-9-]+$/), imageUrl: z.string().trim().url().optional(), imageAlt: z.string().optional(), variants: z.array(variantInput).min(1) })).mutation(async ({ input }) => { try { return await createDbProduct(input); } catch (error) { if (error instanceof Error && error.message === "DUPLICATE_SLUG") throw new TRPCError({ code: "CONFLICT", message: `A product with slug “${input.slug}” already exists. Choose a unique slug.` }); throw error; } }),
    update: adminPortalProcedure.input(z.object({ id: z.number().int().positive(), title: z.string().min(2).optional(), description: z.string().min(1).optional(), category: z.string().min(1).optional(), gender: z.enum(["men", "women", "unisex"]).optional(), slug: z.string().regex(/^[a-z0-9-]+$/).optional(), imageUrl: z.string().trim().url().optional(), imageAlt: z.string().optional(), visible: z.boolean().optional() })).mutation(({ input }) => { const { id, ...changes } = input; return updateDbProduct(id, changes); }),
    updateVariant: adminPortalProcedure.input(z.object({ id: z.number().int().positive(), name: sizeInput.optional(), price: moneyInput.optional(), salePrice: moneyInput.nullable().optional(), discountEnabled: z.boolean().optional(), stock: z.number().int().min(0).optional(), visible: z.boolean().optional() })).mutation(({ input }) => { const { id, ...changes } = input; return updateDbVariant(id, changes); }),
    addVariant: adminPortalProcedure.input(z.object({ productId: z.number().int().positive(), name: sizeInput, price: moneyInput, salePrice: moneyInput.optional(), discountEnabled: z.boolean().optional(), stock: z.number().int().min(0) })).mutation(({ input }) => { const { productId, ...variant } = input; return addDbVariant(productId, variant); }),
    deleteVariant: adminPortalProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => deleteDbVariant(input.id)),
    delete: adminPortalProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input }) => deleteDbProduct(input.id)),
  }),
  images: router({ upload: adminPortalProcedure.input(z.object({ productId: z.number().int().positive(), fileName: z.string().min(1).max(180), mimeType: z.enum(["image/jpeg", "image/png", "image/webp", "image/avif"]), base64: z.string().min(100).max(12_000_000), altText: z.string().max(255).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const buffer = Buffer.from(input.base64.replace(/^data:[^;]+;base64,/, ""), "base64"); const uploaded = await storagePut(`ak-void/products/${input.productId}/${input.fileName}`, buffer, input.mimeType); await db.insert(productImages).values({ productId: input.productId, url: uploaded.url, altText: input.altText ?? input.fileName, sortOrder: 0 }); await db.update(products).set({ imageUrl: uploaded.url, imageAlt: input.altText ?? input.fileName }).where(eq(products.id, input.productId)); return uploaded; }) }),
  bulkImport: adminPortalProcedure.input(z.object({ catalogBase64: z.string().min(100).max(20_000_000), images: z.array(importImage).max(500).default([]) })).mutation(async ({ input }) => {
    const workbook = XLSX.read(Buffer.from(input.catalogBase64.replace(/^data:[^;]+;base64,/, ""), "base64"), { type: "buffer" }); const sheet = workbook.Sheets[workbook.SheetNames[0]]; if (!sheet) throw new TRPCError({ code: "BAD_REQUEST", message: "The catalog file has no worksheet" }); const sourceRows = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "PRECONDITION_FAILED", message: "Database unavailable" }); const existing = new Set((await db.select({ slug: products.slug }).from(products)).map(row => row.slug)); const imageMap = new Map(input.images.map(image => [image.fileName.toLowerCase(), image])); const report = { imported: [] as string[], skipped: [] as Array<{ row: number; reason: string }>, duplicates: [] as Array<{ row: number; slug: string }>, missingImages: [] as Array<{ row: number; fileName: string }>, invalid: [] as Array<{ row: number; reason: string }> };
    for (let index = 0; index < sourceRows.length; index++) { const raw = sourceRows[index]; const row = Object.fromEntries(Object.entries(raw).map(([key, value]) => [cleanHeader(key), value])); const rowNumber = index + 2; const title = String(rowValue(row, "product_name", "product", "title") ?? "").trim(); const slug = String(rowValue(row, "slug") ?? "").trim(); const category = String(rowValue(row, "category") ?? "").trim(); const genderRaw = String(rowValue(row, "gender", "classification") ?? "unisex").trim().toLowerCase(); const gender = genderRaw === "women" || genderRaw === "female" ? "women" : genderRaw === "men" || genderRaw === "male" ? "men" : genderRaw === "unisex" ? "unisex" : null; const priceNumber = Number(rowValue(row, "price") ?? NaN); const imageFiles = String(rowValue(row, "image_filenames", "image_filename", "images", "image", "image_file") ?? "").split(/[,|;]/).map(value => value.trim()).filter(Boolean); if (!title || !slug || !category || !gender || !/^[a-z0-9-]+$/.test(slug) || !Number.isFinite(priceNumber) || priceNumber <= 0) { report.invalid.push({ row: rowNumber, reason: "Required fields, gender, slug, or price is invalid" }); continue; } if (existing.has(slug)) { report.duplicates.push({ row: rowNumber, slug }); continue; } imageFiles.forEach(imageFile => { if (!imageMap.has(imageFile.toLowerCase())) report.missingImages.push({ row: rowNumber, fileName: imageFile }); }); try { const discount = Number(rowValue(row, "discount") ?? 0); const explicitSale = Number(rowValue(row, "sale_price", "sale") ?? NaN); const salePrice = Number.isFinite(explicitSale) && explicitSale > 0 ? explicitSale.toFixed(2) : discount > 0 && discount < 100 ? (priceNumber * (1 - discount / 100)).toFixed(2) : undefined; const variants = parseImportVariants(rowValue(row, "sizes", "size"), rowValue(row, "stock"), priceNumber.toFixed(2), salePrice); const created = await createDbProduct({ title, slug, description: String(rowValue(row, "description") ?? "").trim() || title, category, gender, variants }); const productId = Number(created?.id); if (!Number.isInteger(productId) || productId <= 0) throw new Error("Created product ID is invalid"); for (let imageIndex = 0; imageIndex < imageFiles.length; imageIndex++) { const image = imageMap.get(imageFiles[imageIndex].toLowerCase()); if (!image) continue; const buffer = Buffer.from(image.base64.replace(/^data:[^;]+;base64,/, ""), "base64"); const uploaded = await storagePut(`ak-void/products/${productId}/${image.fileName}`, buffer, image.mimeType); await addDbProductImage(productId, uploaded.url, title, imageIndex); } existing.add(slug); report.imported.push(slug); } catch (error) { report.skipped.push({ row: rowNumber, reason: error instanceof Error ? error.message : "Import failed" }); } }
    return report;
  }),
  orders: router({ list: adminPortalProcedure.query(() => listDbOrders()), updateStatus: adminPortalProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["new", "processing", "shipped", "delivered", "cancelled"]) })).mutation(({ input }) => updateDbOrderStatus(input.id, input.status)) }),
});
